on:
  push:
  pull_request:
name: "rs-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          # - os: windows-2022 # Windows is complete nonsense. If someone wants to figure out how to make tests run there go ahead.
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./

      - name: Windows rust toolchain
        if: runner.os == 'Windows'
        run: |
          find . -name rust-toolchain.toml -exec echo rm {} \;
          rustup component add rust-src --toolchain nightly-2023-06-17-x86_64-pc-windows-gnu
          rustup default nightly-2023-06-17-x86_64-pc-windows-gnu

      - name: Test Fractindex
        run: |
          cd core/rs/fractindex-core
          cargo test --features=loadable_extension

      - name: Integration Tests
        run: |
          cd core/rs/integration-check
          mv ../bundle/Cargo.toml ../bundle/Cargo.toml.bk
          mv ../bundle/Cargo.toml.integration-test ../bundle/Cargo.toml
          cargo test

      - name: Test Core
        run: |
          cd core/rs/core
          cargo test --features=loadable_extension
